#pragma once

#include "LogSink.hpp"
#include <fstream>
#include <regex>


/**
* @brief A log sink that writes messages to a text file.
*
* FileSink receives preformatted strings from the Logger and sequentially
* appends them to the specified file. Before writing, ANSI escape sequences
* (color codes, etc.) are removed so that the file contains "clean" text.
*/
class FileSink : public LogSink
{
public:

    /**
    * @brief Creates a file destination for the specified file.
    *
    * The file is opened in append mode. If the file does not exist,
    * the standard stream usually creates it automatically.
    *
    * @param filename Path to the log file (relative or absolute).
    */
    explicit FileSink(const std::string& filename);

    /**
    * @brief Closes the file stream.
    *
    * Ensures proper resource release and buffer flushing.
    */
    ~FileSink() override;

    /**
    * @brief Writes a log message to a file.
    *
    * ANSI escape sequences are removed from the string before writing,
    * to prevent the file from containing terminal control codes.
    *
    * @param message A completed message string generated by the logger.
    */
    void write(const std::string& message) override;

private:

    /**
    * @brief Removes ANSI escape sequences from a string.
    *
    * Used to clear color codes and other terminal control
    * sequences before writing to a file.
    *
    * @param message The input string, possibly containing ANSI codes.
    * @return The string without ANSI escape sequences.
    */
    static std::string stripAnsi(const std::string& message);

    /// Output stream to the file log.
    std::ofstream file;
};