#pragma once
#include <string>

/**
* @brief The basic interface of a log sink.
*
* Implementations of this class are responsible for the final delivery of generated
* log messages: to the console, file, network, etc. Logger generates a string,
* and LogSink only receives and writes it.
*/
class LogSink
{
public:

    /**
    * @brief Virtual destructor for correct deletion via the base pointer.
    */
    virtual ~LogSink() = default;

    /**
    * @brief Writes a single generated log message.
    *
    * This method must be implemented in derived classes and perform a specific action to deliver the message (output to the console, write to a file, etc.).
    *
    * @param message A ready-made message string generated by the logger.
    */
    virtual void write(const std::string& message) = 0;
};